// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Spatial.Data;

namespace Spatial.Migrations.MSSQL
{
    [DbContext(typeof(MSSQLContext))]
    partial class MSSQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Spatial.Models.RoutePoint", b =>
                {
                    b.Property<int>("RoutePointID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Miles")
                        .HasColumnType("float");

                    b.Property<Point>("Point")
                        .HasColumnType("geography");

                    b.HasKey("RoutePointID");

                    b.ToTable("mssqlpoints");

                    b.HasData(
                        new
                        {
                            RoutePointID = 1,
                            Miles = 0.0,
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.9388777 18.4839233)")
                        },
                        new
                        {
                            RoutePointID = 2,
                            Miles = 0.0,
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.9118804 18.4826214)")
                        },
                        new
                        {
                            RoutePointID = 3,
                            Miles = 0.0,
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.9334673 18.4718075)")
                        },
                        new
                        {
                            RoutePointID = 4,
                            Miles = 0.0,
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-99.1353659 19.4336164)")
                        },
                        new
                        {
                            RoutePointID = 5,
                            Miles = 0.0,
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-0.2416804 51.5285582)")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
